<?php

namespace Database\Seeders;

use App\Models\KeywordPage;
use Illuminate\Database\Seeder;

class KeywordPageSeeder extends Seeder
{
    public function run(): void
    {
        $pages = array_merge(
            $this->existingPages(),
            $this->newTop20Pages(),
        );

        foreach ($pages as $page) {
            KeywordPage::updateOrCreate(
                ['slug' => $page['slug']],
                $page
            );
        }
    }

    private function existingPages(): array
    {
        return [
            [
                'slug' => 'ledai',
                'title' => 'Ledai',
                'emoji' => '🍦',
                'grammar_plural' => 'ledai',
                'grammar_genitive' => 'ledų',
                'grammar_dative' => 'ledams',
                'h1' => 'Ledų akcijos ir nuolaidos šią savaitę',
                'meta_title' => 'Ledų akcija – pigiausia kaina šią savaitę | SuperAkcijos.lt',
                'meta_description' => 'Ledų akcija visuose prekybos tinkluose. Kur pigiausia ledai? Palyginkite grietininės, vaisinės ir premium ledų kainas MAXIMA, IKI, LIDL, RIMI ir kitose parduotuvėse.',
                'search_terms' => ['ledai', 'ledų', 'ledas', 'ice cream'],
                'category_slugs' => ['saldytas-maistas-ir-ledai'],
                'exclude_terms' => ['ledinis', 'ledinis kremas'],
                'intro_html' => '<p>Ledai – mėgstamiausias desertas tiek vaikams, tiek suaugusiesiems. Lietuvos parduotuvėse rasite didžiulį ledų pasirinkimą – nuo klasikinių grietininėlių iki vaisinių ir premium ledų. SuperAkcijos.lt surenka visas ledų akcijas vienoje vietoje.</p>',
                'tips' => [
                    ['icon' => '📦', 'title' => 'Pirkite multipakus', 'text' => 'Ledų multipakuotės akcijų metu kainuoja žymiai pigiau už atskirus batonėlius.'],
                    ['icon' => '☀️', 'title' => 'Stebėkite vasaros akcijas', 'text' => 'Birželį–rugpjūtį ledų akcijos būna dažniausios ir didžiausios.'],
                    ['icon' => '⚖️', 'title' => 'Palyginkite kainą už kg', 'text' => 'Pakuotės labai skiriasi dydžiu – visada palyginkite kainą už kilogramą.'],
                    ['icon' => '🇱🇹', 'title' => 'Išbandykite lietuviškus gamintojus', 'text' => 'Dadu, Karališki ir Aurum ledai dažnai konkuruoja kokybe su importiniais prekės ženklais.'],
                ],
                'faq' => [
                    ['question' => 'Kur pigiausia ledai?', 'answer' => 'Kainos kiekvieną savaitę skiriasi – naudokite SuperAkcijos.lt palyginimą ir filtruokite pagal parduotuvę.'],
                    ['question' => 'Kokie ledų tipai populiariausi Lietuvoje?', 'answer' => 'Populiariausi yra grietininėliai ledai, vaisiniai ledai, ledų batoneliai ir šeimyninės dėžutės.'],
                    ['question' => 'Kaip teisingai laikyti ledus namuose?', 'answer' => 'Laikykite šaldiklyje –18°C ar žemesnėje temperatūroje. Atidarytą dėžutę uždenkite, kad nesugertų pašalinių kvapų.'],
                    ['question' => 'Kada geriausia pirkti ledus su nuolaidomis?', 'answer' => 'Didžiausios ledų akcijos būna pavasario pabaigoje ir vasarą, tačiau geras nuolaidas galima rasti ir žiemą.'],
                ],
                'related_slugs' => ['saldainiai', 'sokoladas', 'pienas'],
                'sort_order' => 10,
                'min_active_offers' => 1,
                'is_published' => true,
            ],
            [
                'slug' => 'saldainiai',
                'title' => 'Saldainiai',
                'emoji' => '🍭',
                'grammar_plural' => 'saldainiai',
                'grammar_genitive' => 'saldainių',
                'grammar_dative' => 'saldainiams',
                'h1' => 'Saldainių akcijos ir nuolaidos šią savaitę',
                'meta_title' => 'Saldainių akcija – pigiausia kaina šią savaitę | SuperAkcijos.lt',
                'meta_description' => 'Saldainių akcija visuose prekybos tinkluose. Kur pigiausia saldainiai? Palyginkite šokoladinius, karamelinius ir vaikiškus saldainius su nuolaidomis.',
                'search_terms' => ['saldainiai', 'saldainių', 'saldainis', 'saldain'],
                'category_slugs' => ['saldumynai-ir-uzkandziai'],
                'exclude_terms' => [],
                'intro_html' => '<p>Saldainiai – vienas populiariausių užkandžių Lietuvoje. Nuo šokoladinių batonėlių iki karamelinių ir vaikiškų saldainių – SuperAkcijos.lt padeda rasti geriausias kainas.</p>',
                'tips' => [
                    ['icon' => '🎁', 'title' => 'Pirkite didesnes pakuotes', 'text' => 'Didelės saldainių dėžutės šventėms dažnai būna pigesnės už mažas pakuotes.'],
                    ['icon' => '🍫', 'title' => 'Sekite šokolado akcijas', 'text' => 'Šokoladiniai saldainiai dažnai akcijuojami kartu su šokoladu – palyginkite abu puslapius.'],
                ],
                'faq' => [
                    ['question' => 'Kur pigiausia saldainiai?', 'answer' => 'Kainos skiriasi kiekvieną savaitę – naudokite SuperAkcijos.lt palyginimą ir filtruokite pagal parduotuvę.'],
                    ['question' => 'Ar saldainių akcijos galioja su lojalumo kortele?', 'answer' => 'Kai kurios akcijos reikalauja parduotuvės kortelės – žiūrėkite žymėjimą prie kiekvieno pasiūlymo.'],
                ],
                'related_slugs' => ['sokoladas', 'ledai'],
                'sort_order' => 20,
                'min_active_offers' => 1,
                'is_published' => true,
            ],
            [
                'slug' => 'saslikai',
                'title' => 'Šašlikai',
                'emoji' => '🍢',
                'grammar_plural' => 'šašlykai',
                'grammar_genitive' => 'šašlykų',
                'grammar_dative' => 'šašlykams',
                'h1' => 'Šašlikų akcijos ir nuolaidos šią savaitę',
                'meta_title' => 'Šašlikų akcija – pigiausia kaina šią savaitę | SuperAkcijos.lt',
                'meta_description' => 'Šašlikų akcija visuose prekybos tinkluose. Kur pigiausia šašlykai? Palyginkite marinuotų ir šviežių šašlikų kainas MAXIMA, IKI, LIDL, RIMI ir kitose parduotuvėse.',
                'search_terms' => ['šašlyk', 'saslyk', 'šašlykas', 'saslykas', 'šašlik', 'saslik'],
                'category_slugs' => ['mesa-ir-zuvis'],
                'exclude_terms' => [],
                'intro_html' => '<p>Šašlikai – sezono favoritas grilio sezonui ir šeimos pietums. Palyginkite marinuotų ir šviežių šašlikų kainas visuose pagrindiniuose prekybos tinkluose.</p>',
                'tips' => [
                    ['icon' => '🔥', 'title' => 'Sekite sezonines akcijas', 'text' => 'Didžiausios šašlikų akcijos būna pavasarį ir vasarą, prieš grilio sezoną.'],
                    ['icon' => '🥩', 'title' => 'Palyginkite svorį', 'text' => 'Pakuotės svoris skiriasi – žiūrėkite kainą už kilogramą.'],
                ],
                'faq' => [
                    ['question' => 'Kur pigiausia šašlykai?', 'answer' => 'Kainos kiekvieną savaitę skiriasi – naudokite SuperAkcijos.lt palyginimą ir filtruokite pagal parduotuvę.'],
                    ['question' => 'Kokie šašlikai populiariausi?', 'answer' => 'Populiariausi yra vištienos ir kiaulienos šašlikai, dažnai marinuoti su daržovėmis.'],
                ],
                'related_slugs' => ['mesa', 'ledai'],
                'sort_order' => 30,
                'min_active_offers' => 1,
                'is_published' => true,
            ],
            [
                'slug' => 'sokoladas',
                'title' => 'Šokoladas',
                'emoji' => '🍫',
                'grammar_plural' => 'šokoladas',
                'grammar_genitive' => 'šokolado',
                'grammar_dative' => 'šokoladui',
                'h1' => 'Šokolado akcijos ir nuolaidos šią savaitę',
                'meta_title' => 'Šokolado akcija – pigiausia kaina šią savaitę | SuperAkcijos.lt',
                'meta_description' => 'Šokolado akcija visuose prekybos tinkluose. Kur pigiausia šokoladas? Palyginkite tabletes, batonėlius ir premium šokoladą su nuolaidomis.',
                'search_terms' => ['šokolad', 'sokolad', 'šokoladas', 'sokoladas'],
                'category_slugs' => ['saldumynai-ir-uzkandziai'],
                'exclude_terms' => ['šokoladiniai saldainiai'],
                'intro_html' => '<p>Šokoladas – vienas dažniausiai akcijuojamų saldumynų. Nuo pieninio iki juodojo ir premium šokolado – raskite geriausias kainas vienoje vietoje.</p>',
                'tips' => [],
                'faq' => [
                    ['question' => 'Kur pigiausia šokoladas?', 'answer' => 'Kainos skiriasi kiekvieną savaitę – naudokite SuperAkcijos.lt palyginimą ir filtruokite pagal parduotuvę.'],
                ],
                'related_slugs' => ['saldainiai', 'ledai'],
                'sort_order' => 40,
                'min_active_offers' => 1,
                'is_published' => true,
            ],
            [
                'slug' => 'pienas',
                'title' => 'Pienas',
                'emoji' => '🥛',
                'grammar_plural' => 'pienas',
                'grammar_genitive' => 'pieno',
                'grammar_dative' => 'pienui',
                'h1' => 'Pieno akcijos ir nuolaidos šią savaitę',
                'meta_title' => 'Pieno akcija – pigiausia kaina šią savaitę | SuperAkcijos.lt',
                'meta_description' => 'Pieno akcija MAXIMA, IKI, LIDL, RIMI ir kitose parduotuvėse. Kur pigiausia pienas? Palyginkite pieno pasiūlymus ir sutaupykite kas savaitę.',
                'search_terms' => ['pienas', 'pieno', 'pien'],
                'category_slugs' => ['pieno-produktai-ir-kiausiniai'],
                'exclude_terms' => ['pieno šokolad'],
                'intro_html' => '<p>Pienas – kasdienis produktas, kurio kaina svarbi kiekvienam pirkėjui. Stebėkite savaitės akcijas ir sutaupykite.</p>',
                'tips' => [],
                'faq' => [
                    ['question' => 'Kur pigiausia pienas?', 'answer' => 'Kainos skiriasi kiekvieną savaitę – naudokite SuperAkcijos.lt palyginimą ir filtruokite pagal parduotuvę.'],
                ],
                'related_slugs' => ['sviestas', 'suris', 'ledai'],
                'sort_order' => 50,
                'min_active_offers' => 1,
                'is_published' => true,
            ],
            [
                'slug' => 'kava',
                'title' => 'Kava',
                'emoji' => '☕',
                'grammar_plural' => 'kava',
                'grammar_genitive' => 'kavos',
                'grammar_dative' => 'kavai',
                'h1' => 'Kavos akcijos ir nuolaidos šią savaitę',
                'meta_title' => 'Kavos akcija – pigiausia kaina šią savaitę | SuperAkcijos.lt',
                'meta_description' => 'Kavos akcija visuose prekybos tinkluose. Kur pigiausia kava? Palyginkite maltos kavos, pupelių ir kapsulių akcijas MAXIMA, IKI, LIDL, RIMI ir kitose parduotuvėse.',
                'search_terms' => ['kava', 'kavos', 'kav'],
                'category_slugs' => ['gerimai-kava-arbata'],
                'exclude_terms' => [],
                'intro_html' => '<p>Kava – vienas populiariausių gėrimų. Palyginkite maltos kavos, pupelių ir kapsulių akcijas visuose pagrindiniuose prekybos tinkluose.</p>',
                'tips' => [],
                'faq' => [
                    ['question' => 'Kur pigiausia kava?', 'answer' => 'Kainos kiekvieną savaitę skiriasi – naudokite SuperAkcijos.lt palyginimą ir filtruokite pagal parduotuvę.'],
                    ['question' => 'Kada dažniausiai būna kavos akcijos?', 'answer' => 'Kavos akcijos pasirodo reguliariai visuose tinkluose – ypač didesnės nuolaidos būna šventėms ir rudens sezonui.'],
                ],
                'related_slugs' => [],
                'sort_order' => 60,
                'min_active_offers' => 1,
                'is_published' => true,
            ],
        ];
    }

    private function newTop20Pages(): array
    {
        return [
            $this->page(
                slug: 'alus',
                title: 'Alus',
                emoji: '🍺',
                plural: 'alus',
                genitive: 'alaus',
                dative: 'alui',
                searchTerms: ['alus', 'alaus', 'al'],
                categorySlugs: ['alkoholiniai-ir-nealkoholiniai-gerimai'],
                excludeTerms: ['nealkoholinis alus'],
                intro: 'Alus – vienas populiariausių gėrimų Lietuvoje. Palyginkite alaus akcijas visuose pagrindiniuose prekybos tinkluose.',
                related: ['kava'],
                sortOrder: 70,
            ),
            $this->page(
                slug: 'arbuzas',
                title: 'Arbūzas',
                emoji: '🍉',
                plural: 'arbūzai',
                genitive: 'arbūzų',
                dative: 'arbūzams',
                searchTerms: ['arbūz', 'arbuza', 'arbuz'],
                categorySlugs: ['vaisiai-ir-darzoves'],
                excludeTerms: [],
                intro: 'Arbūzas – vasaros sezono favoritas. Stebėkite arbūzų akcijas ir palyginkite kainas parduotuvėse.',
                related: ['persikai', 'braskes', 'agurkai'],
                sortOrder: 80,
            ),
            $this->page(
                slug: 'persikai',
                title: 'Persikai',
                emoji: '🍑',
                plural: 'persikai',
                genitive: 'persikų',
                dative: 'persikams',
                searchTerms: ['persik', 'persikai', 'persikų'],
                categorySlugs: ['vaisiai-ir-darzoves'],
                excludeTerms: [],
                intro: 'Persikai – mėgstamas vasaros vaisius. Palyginkite persikų akcijas visuose prekybos tinkluose.',
                related: ['vysnios', 'arbuzas', 'braskes'],
                sortOrder: 90,
            ),
            $this->page(
                slug: 'vysnios',
                title: 'Vyšnios',
                emoji: '🍒',
                plural: 'vyšnios',
                genitive: 'vyšnių',
                dative: 'vyšnioms',
                searchTerms: ['vyšn', 'vysn', 'vyšnių', 'vysniu'],
                categorySlugs: ['vaisiai-ir-darzoves'],
                excludeTerms: [],
                intro: 'Vyšnios – sezoninis vaisius su dažnomis akcijomis vasarą. Palyginkite vyšnių kainas parduotuvėse.',
                related: ['persikai', 'braskes', 'silauoges'],
                sortOrder: 100,
                isPublished: true,
            ),
            $this->page(
                slug: 'braskes',
                title: 'Braškės',
                emoji: '🍓',
                plural: 'braškės',
                genitive: 'braškių',
                dative: 'braškėms',
                searchTerms: ['brašk', 'brask', 'braškių', 'braskiu'],
                categorySlugs: ['vaisiai-ir-darzoves'],
                excludeTerms: ['braškių uogienė', 'braškių džemas'],
                intro: 'Braškės – vienas populiariausių vasaros vaisių. Stebėkite braškių akcijas ir raskite geriausią kainą.',
                related: ['silauoges', 'vysnios', 'persikai'],
                sortOrder: 110,
                isPublished: true,
            ),
            $this->page(
                slug: 'silauoges',
                title: 'Šilauogės',
                emoji: '🫐',
                plural: 'šilauogės',
                genitive: 'šilauogių',
                dative: 'šilauogėms',
                searchTerms: ['šilauog', 'silauog', 'mėlyn', 'melyn'],
                categorySlugs: ['vaisiai-ir-darzoves'],
                excludeTerms: ['mėlynas sūris'],
                intro: 'Šilauogės – populiarus vasaros uogų pasirinkimas. Palyginkite šilauogių akcijas visuose tinkluose.',
                related: ['braskes', 'vysnios'],
                sortOrder: 120,
            ),
            $this->page(
                slug: 'aliejus',
                title: 'Aliejus',
                emoji: '🫒',
                plural: 'aliejus',
                genitive: 'aliejaus',
                dative: 'aliejui',
                searchTerms: ['aliej', 'aliejus', 'aliejaus', 'alyvu'],
                categorySlugs: ['bakaleja'],
                excludeTerms: ['kremas aliej'],
                intro: 'Aliejus – kasdienis bakalėjos produktas. Palyginkite saulėgrąžų, rapsų ir alyvuogių aliejaus akcijas.',
                related: ['cukrus', 'miltai'],
                sortOrder: 130,
            ),
            $this->page(
                slug: 'mesa',
                title: 'Mėsa',
                emoji: '🥩',
                plural: 'mėsa',
                genitive: 'mėsos',
                dative: 'mėsai',
                searchTerms: ['mėsa', 'mesa', 'mėsos', 'mesos'],
                categorySlugs: ['mesa-ir-zuvis'],
                excludeTerms: ['mėsainis', 'mesainis', 'mėsos sultinys'],
                intro: 'Mėsa – viena svarbiausių savaitės pirkinių kategorijų. Palyginkite mėsos akcijas visuose prekybos tinkluose.',
                related: ['saslikai', 'kiausiniai'],
                sortOrder: 140,
            ),
            $this->page(
                slug: 'cukrus',
                title: 'Cukrus',
                emoji: '🧂',
                plural: 'cukrus',
                genitive: 'cukraus',
                dative: 'cukrui',
                searchTerms: ['cukr', 'cukrus', 'cukraus'],
                categorySlugs: ['bakaleja'],
                excludeTerms: ['cukriniai saldainiai', 'be cukraus'],
                intro: 'Cukrus – pagrindinis bakalėjos produktas. Stebėkite cukraus akcijas ir sutaupykite kas savaitę.',
                related: ['miltai', 'aliejus'],
                sortOrder: 150,
            ),
            $this->page(
                slug: 'kiausiniai',
                title: 'Kiaušiniai',
                emoji: '🥚',
                plural: 'kiaušiniai',
                genitive: 'kiaušinių',
                dative: 'kiaušiniams',
                searchTerms: ['kiaušin', 'kiausin', 'kiaušini', 'kiaušiniai', 'kiausiniai', 'kiaušinių'],
                categorySlugs: ['pieno-produktai-ir-kiausiniai'],
                excludeTerms: ['kiaušinienė', 'kiausiniene'],
                intro: 'Kiaušiniai – kasdienis produktas kiekvienam pirkiniui. Palyginkite kiaušinių akcijas visuose tinkluose.',
                related: ['pienas', 'sviestas', 'mesa'],
                sortOrder: 160,
                isPublished: true,
            ),
            $this->page(
                slug: 'sviestas',
                title: 'Sviestas',
                emoji: '🧈',
                plural: 'sviestas',
                genitive: 'sviesto',
                dative: 'sviestui',
                searchTerms: ['sviest', 'sviestas', 'sviesto'],
                categorySlugs: ['pieno-produktai-ir-kiausiniai'],
                excludeTerms: ['sviestinis kremas', 'be sviesto'],
                intro: 'Sviestas – svarbus pieno produktų pasirinkimas. Palyginkite sviesto akcijas ir raskite geriausią kainą.',
                related: ['pienas', 'suris', 'kiausiniai'],
                sortOrder: 170,
            ),
            $this->page(
                slug: 'miltai',
                title: 'Miltai',
                emoji: '🌾',
                plural: 'miltai',
                genitive: 'miltų',
                dative: 'miltams',
                searchTerms: ['milt', 'miltai', 'miltų', 'miltu'],
                categorySlugs: ['bakaleja'],
                excludeTerms: ['milteliai', 'miltel'],
                intro: 'Miltai – pagrindinis kepimo ingredientas. Stebėkite miltų akcijas visuose prekybos tinkluose.',
                related: ['cukrus', 'aliejus'],
                sortOrder: 180,
            ),
            $this->page(
                slug: 'pomidorai',
                title: 'Pomidorai',
                emoji: '🍅',
                plural: 'pomidorai',
                genitive: 'pomidorų',
                dative: 'pomidorams',
                searchTerms: ['pomidor', 'pomidorai', 'pomidorų'],
                categorySlugs: ['vaisiai-ir-darzoves'],
                excludeTerms: ['pomidorų padažas', 'pomidorų sultys', 'kečupas'],
                intro: 'Pomidorai – vienas populiariausių daržovių. Palyginkite pomidorų akcijas ir sutaupykite.',
                related: ['agurkai', 'morkos', 'bulves'],
                sortOrder: 190,
            ),
            $this->page(
                slug: 'agurkai',
                title: 'Agurkai',
                emoji: '🥒',
                plural: 'agurkai',
                genitive: 'agurkų',
                dative: 'agurkams',
                searchTerms: ['agurk', 'agurkai', 'agurkų'],
                categorySlugs: ['vaisiai-ir-darzoves'],
                excludeTerms: ['marinuoti agurkai'],
                intro: 'Agurkai – sezoninis ir kasdienis daržovių pasirinkimas. Palyginkite agurkų akcijas parduotuvėse.',
                related: ['pomidorai', 'morkos', 'arbuzas'],
                sortOrder: 200,
            ),
            $this->page(
                slug: 'bulves',
                title: 'Bulvės',
                emoji: '🥔',
                plural: 'bulvės',
                genitive: 'bulvių',
                dative: 'bulvėms',
                searchTerms: ['bulv', 'bulvės', 'bulves', 'bulvių'],
                categorySlugs: ['vaisiai-ir-darzoves'],
                excludeTerms: ['bulvių traškučiai', 'bulvių drožlės'],
                intro: 'Bulvės – vienas populiariausių daržovių. Stebėkite bulvių akcijas visuose prekybos tinkluose.',
                related: ['morkos', 'svogunai', 'pomidorai'],
                sortOrder: 210,
            ),
            $this->page(
                slug: 'morkos',
                title: 'Morkos',
                emoji: '🥕',
                plural: 'morkos',
                genitive: 'morkų',
                dative: 'morkoms',
                searchTerms: ['mork', 'morkos', 'morkų'],
                categorySlugs: ['vaisiai-ir-darzoves'],
                excludeTerms: ['morkų sultys'],
                intro: 'Morkos – kasdienis daržovių pasirinkimas. Palyginkite morkų akcijas ir raskite geriausią kainą.',
                related: ['bulves', 'svogunai', 'pomidorai'],
                sortOrder: 220,
            ),
            $this->page(
                slug: 'svogunai',
                title: 'Svogūnai',
                emoji: '🧅',
                plural: 'svogūnai',
                genitive: 'svogūnų',
                dative: 'svogūnams',
                searchTerms: ['svogūn', 'svogun', 'svogūnų'],
                categorySlugs: ['vaisiai-ir-darzoves'],
                excludeTerms: [],
                intro: 'Svogūnai – pagrindinis virtuvės produktas. Stebėkite svogūnų akcijas visuose tinkluose.',
                related: ['morkos', 'bulves', 'pomidorai'],
                sortOrder: 230,
                isPublished: true,
            ),
            $this->page(
                slug: 'bananai',
                title: 'Bananai',
                emoji: '🍌',
                plural: 'bananai',
                genitive: 'bananų',
                dative: 'bananams',
                searchTerms: ['banan', 'bananai', 'bananų'],
                categorySlugs: ['vaisiai-ir-darzoves'],
                excludeTerms: ['bananų traškučiai'],
                intro: 'Bananai – populiariausias vaisius ištisus metus. Palyginkite bananų akcijas parduotuvėse.',
                related: ['obuoliai', 'persikai'],
                sortOrder: 240,
                isPublished: false,
            ),
            $this->page(
                slug: 'obuoliai',
                title: 'Obuoliai',
                emoji: '🍎',
                plural: 'obuoliai',
                genitive: 'obuolių',
                dative: 'obuoliams',
                searchTerms: ['obuol', 'obuoliai', 'obuolių'],
                categorySlugs: ['vaisiai-ir-darzoves'],
                excludeTerms: ['obuolių sultys', 'obuolių sidras'],
                intro: 'Obuoliai – sezoninis ir kasdienis vaisius. Stebėkite obuolių akcijas visuose prekybos tinkluose.',
                related: ['bananai', 'persikai'],
                sortOrder: 250,
            ),
            $this->page(
                slug: 'suris',
                title: 'Sūris',
                emoji: '🧀',
                plural: 'sūris',
                genitive: 'sūrio',
                dative: 'sūriui',
                searchTerms: ['sūr', 'suris', 'sūri', 'sūrio'],
                categorySlugs: ['pieno-produktai-ir-kiausiniai'],
                excludeTerms: ['sūrio užtepėl'],
                intro: 'Sūris – populiarus pieno produktas. Palyginkite sūrio akcijas MAXIMA, IKI, LIDL, RIMI ir kitose parduotuvėse.',
                related: ['pienas', 'sviestas', 'kiausiniai'],
                sortOrder: 260,
            ),
        ];
    }

    private function page(
        string $slug,
        string $title,
        string $emoji,
        string $plural,
        string $genitive,
        string $dative,
        array $searchTerms,
        array $categorySlugs,
        array $excludeTerms,
        string $intro,
        array $related,
        int $sortOrder,
        bool $isPublished = true,
    ): array {
        $titleLower = mb_strtolower($title);

        return [
            'slug' => $slug,
            'title' => $title,
            'emoji' => $emoji,
            'grammar_plural' => $plural,
            'grammar_genitive' => $genitive,
            'grammar_dative' => $dative,
            'h1' => $genitive . ' akcijos ir nuolaidos šią savaitę',
            'meta_title' => ucfirst($genitive) . ' akcija – pigiausia kaina šią savaitę | SuperAkcijos.lt',
            'meta_description' => ucfirst($genitive) . ' akcija visuose prekybos tinkluose. Kur pigiausia ' . $titleLower . '? Palyginkite akcijas MAXIMA, IKI, LIDL, RIMI ir kitose parduotuvėse.',
            'search_terms' => $searchTerms,
            'category_slugs' => $categorySlugs,
            'exclude_terms' => $excludeTerms,
            'intro_html' => '<p>' . $intro . '</p>',
            'tips' => [],
            'faq' => [
                [
                    'question' => 'Kur pigiausia ' . $titleLower . '?',
                    'answer' => 'Kainos kiekvieną savaitę skiriasi – naudokite SuperAkcijos.lt palyginimą ir filtruokite pagal parduotuvę.',
                ],
            ],
            'related_slugs' => $related,
            'sort_order' => $sortOrder,
            'min_active_offers' => 1,
            'is_published' => $isPublished,
        ];
    }
}
