<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
  private const CHIP_TITLES = [
    'Kava',
    'Lašiša',
    'Lego',
    'Skalbimo priemonės',
    'Saldainiai',
    'Bulvės',
    'Sviestas',
    'Vanduo',
    'Cola',
    'Žuvų taukai',
    'Kumpis',
    'Aliejus',
    'Nutella',
    'Karpis',
    'Antis',
    'Whiskas',
    'Tofu kraikas',
    'Sheba',
    'Morkos',
    'Pistacijos',
    'Mokyklinės prekės',
    'Akumuliatoriai',
    'Kiaušiniai',
    'Lagaminai',
    'Popieriniai rankšluosčiai',
    'Ikrai',
    'Krevetės',
    'Sushi',
    'Žuvis',
    'Upėtakis',
    'Pica',
    'Ferrero Rocher',
    'Kondensuotas pienas',
    'Pagalvės',
    'Kiaulienos sprandinė',
    'Automobilių prekės',
    'Aptamil 2',
    'Texas anglys',
    'Majonezas',
    'Pampers',
    'Milka',
    'Skumbrė',
    'Pedigree',
    'Protezų klijai',
    'Pringles',
    'Vytautas',
    'Raffaello',
    'Džiugo sūris',
    'Langų skystis',
    'Kremai nuo saulės',
    'Pepsi',
    'Red Bull',
    'Agurkai',
    'Tigrinės krevetės',
    'Monster',
    'Varškė',
    'Vištienos krūtinėlė',
    'Sauskelnės',
    'Vištiena',
    'Švieži kopūstai',
    'Cukrus',
    'Citrinos',
    'Pomidorai',
    'Bananai',
    'Obuoliai',
    'Apelsinai',
    'Vynuogės',
    'Salotos',
    'Svogūnai',
    'Česnakai',
    'Paprikos',
    'Avokadai',
    'Pienas',
    'Sūris',
    'Jogurtas',
    'Grietinė',
    'Kefyras',
    'Grietinėlė',
    'Varškės sūreliai',
    'Mozzarella',
    'Fermentinis sūris',
    'Duona',
    'Batonas',
    'Bandelės',
    'Tortilijos',
    'Lavašas',
    'Sumuštinių duona',
    'Juoda duona',
    'Skrudinimo duona',
    'Pyragai',
    'Kruasanai',
    'Kiauliena',
    'Jautiena',
    'Faršas',
    'Dešrelės',
    'Dešra',
    'Šoninė',
    'Vištienos šlaunelės',
    'Mėsos gaminiai',
    'Silkė',
    'Ledai',
    'Šaldyta pica',
    'Šaldytos daržovės',
    'Šaldytos uogos',
    'Šaldyti koldūnai',
    'Šaldyti cepelinai',
    'Šaldyti žuvies piršteliai',
    'Šaldyta žuvis',
    'Šaldyti pusgaminiai',
    'Šaldytos bulvytės',
    'Makaronai',
    'Ryžiai',
    'Grikiai',
    'Miltai',
    'Konservai',
    'Padažai',
    'Kečupas',
    'Prieskoniai',
    'Druska',
    'Kruopos',
    'Avižos',
    'Sriubos',
    'Uogienė',
    'Medus',
    'Actas',
    'Kūdikių maistas',
    'Mišinukai',
    'Tyrelės',
    'Drėgnos servetėlės',
    'Kūdikių košės',
    'Vaikiški užkandžiai',
    'Vaikų higiena',
    'Žindukai',
    'Buteliukai',
    'Šokoladas',
    'Sausainiai',
    'Traškučiai',
    'Riešutai',
    'Vafliai',
    'Batonėliai',
    'Batoneliai',
    'Guminukai',
    'Zefyrai',
    'Popkornai',
    'Užkandžiai',
    'Arbata',
    'Sultys',
    'Gazuoti gėrimai',
    'Energetiniai gėrimai',
    'Kavos kapsulės',
    'Tirpi kava',
    'Malta kava',
    'Kakava',
    'Alus',
    'Nealkoholinis alus',
    'Vynas',
    'Šampanas',
    'Sidras',
    'Nealkoholiniai gėrimai',
    'Tonic',
    'Šampūnai',
    'Dušo želė',
    'Dantų pasta',
    'Dantų šepetėliai',
    'Dezodorantai',
    'Muilas',
    'Tualetinis popierius',
    'Higieniniai įklotai',
    'Tamponai',
    'Skustuvai',
    'Veido kremas',
    'Kūno kremas',
    'Plaukų dažai',
    'Burnos higiena',
    'Skalbiklis',
    'Skalbimo kapsulės',
    'Skalbimo milteliai',
    'Indų plovikliai',
    'Indaplovių tabletės',
    'Valikliai',
    'Tualeto valikliai',
    'Grindų valikliai',
    'Šiukšlių maišai',
    'Kempinėlės',
    'Dezinfekcinės priemonės',
    'Anglys',
    'Grilio prekės',
    'Sodo prekės',
    'Virtuvės reikmenys',
    'Puodai',
    'Keptuvės',
    'Baterijos',
    'Lemputės',
    'Įrankiai',
    'Tekstilė',
    'Patalynė',
    'Žaislai',
    'Kanceliarinės prekės',
    'Kačių maistas',
    'Šunų maistas',
    'Kačių kraikas',
    'Gyvūnų skanėstai',
    'Konservai katėms',
    'Konservai šunims',
    'Sausas kačių maistas',
    'Sausas šunų maistas',
    'Kraikas',
    'Gyvūnų higiena',
    'Gėlės',
    'Augalai',
    'Kambariniai augalai',
    'Lauko augalai',
    'Sėklos',
    'Žemė augalams',
    'Trąšos',
    'Vazonai',
    'Daigai',
    'Sodinukai',
    'Skintos gėlės',
    'Orchidėjos',
    'Kapų žvakės',
  ];

  public function up(): void
  {
    Schema::table('keyword_pages', function (Blueprint $table) {
      $table->boolean('is_chip')->default(false)->after('is_published');
    });

    DB::table('keyword_pages')
      ->whereIn('title', self::CHIP_TITLES)
      ->update(['is_chip' => true]);
  }

  public function down(): void
  {
    Schema::table('keyword_pages', function (Blueprint $table) {
      $table->dropColumn('is_chip');
    });
  }
};
