<?php

// Canonical store => flyer-scraper filename map, shared by flyers:scrape.
return [
    'Maxima' => 'maxima.js',
    'Lidl' => 'lidl.js',
    'Norfa' => 'norfa.js',
    'Rimi' => 'rimi.js',
    'Iki' => 'iki.js',
    'Aibė' => 'aibe.js',
    'Šilas' => 'silas.js',
    'Koops' => 'koops.js',
    'Kubas' => 'kubas.js',
    'Čia' => 'cia.js',
    'Thomas Philipps' => 'thomas-philipps.js',
    'Vynoteka' => 'vynoteka.js',
    'Grustė' => 'gruste.js',
    'Gulbelė' => 'gulbele.js',
    'Eurokos' => 'eurokos.js',
    'Jysk' => 'jysk.js',
    'Senukai' => 'senukai.js',
    'Eurovaistinė' => 'eurovaistine.js',
    'Camelia' => 'camelia.js',
    'Moki Veži' => 'moki-vezi.js',
    'Ermitažas' => 'ermitazas.js',
    'Elimart' => 'elimart.js',
    'Gintarinė vaistinė' => 'gintarine-vaistine.js',
    'TECHasas' => 'techasas.js',
    'Bikuva' => 'bikuva.js',
    'Apotheka' => 'apotheka.js',
    'Benu vaistinė' => 'benu-vaistine.js',
    'N vaistinė' => 'n-vaistine.js',
    'Ramunėlės vaistinė' => 'ramuneles-vaistine.js',
    'Mary Kay' => 'mary-kay.js',
    'AVS' => 'avs.js',
    'Lankava' => 'lankava.js',
    'Jupoja' => 'jupoja.js',
    'Express Market' => 'express-market.js',
    'ePromo' => 'epromo.js',
    'Promo Cash&Carry' => 'promo-cash-carry.js',
    'Švaros Prekės' => 'svaros-prekes.js',
    'Oriflame' => 'oriflame.js',
    'Officeday' => 'officeday.js',
    'Avon' => 'avon.js',
];
